#
# The "buildscript.properties" file contains settings loaded and used by the "build.gradle" file.
# For settings loaded in all gradle files or custom settings, use "gradle.properties" instead.
# New properties should not be created in this file, use "gradle.properties" instead.
#

# The name of your mod. Can be any sequence of characters.
modName = Realistic NTM

# This is a case-sensitive string to identify your mod.
# Must be less than 64 characters and all lowercase. Convention is to only contain alphabetic characters.
modId = realisticntm

# Project package location.
modGroup = com.realisticntm

# Version of your mod.
modVersion = 1.0.0

# Whether to use the old jar naming structure (modid-mcversion-version) instead of the new version (modid-version)
includeMCVersionJar = false

# The name of your jar when you produce builds, not including any versioning info
modArchivesBaseName = Realistic-NTM-CE-addon

# Will update your build.gradle automatically whenever an update is available
autoUpdateBuildScript = false

minecraftVersion = 1.12.2

# Select a username for testing your mod with breakpoints.
developmentEnvironmentUserName = Dev

# Additional arguments applied to the JVM when launching minecraft
additionalJavaArguments =

# Enables using modern java syntax (up to version 17) via Jabel, while still targeting JVM 8.
enableModernJavaSyntax = true

# Enables runClient/runServer tasks for Java 17 and Java 21 using LWJGL3ify.
enableJava17RunTasks = false

# Generate a class with String fields for the mod id, name and version named with the fields below
generateGradleTokenClass = com.realisticntm.Tags
gradleTokenModId = MODID
gradleTokenModName = MODNAME
gradleTokenVersion = VERSION

# In case your mod provides an API for other mods to implement you may declare its package here.
apiPackage =

useSrcApiPath = false

# Specify the configuration file for Forge's access transformers here. It must be placed into /src/main/resources/
accessTransformersFile =

# Provides setup for Mixins if enabled.
usesMixins = true
mixinProviderSpec = zone.rong:mixinbooter:10.7
mixinsPackage = mixin
mixinConfigRefmap =
generateMixinConfig = false
coreModClass =
containsMixinsAndOrCoreModOnly = false

forceEnableMixins = false

enableCoreModDebug = false

includeWellKnownRepositories = true

includeCommonDevEnvMods = true

stripForgeRequirements = false

usesShadowedDependencies = false
minimizeShadowedDependencies = true
relocateShadowedDependencies = true

separateRunDirectories = true

versionDisplayFormat = $MOD_NAME \u2212 $VERSION

modrinthProjectId =

modrinthRelations =

curseForgeProjectId =

curseForgeRelations =

releaseType = release

generateDefaultChangelog = false

noPublishedSources = false

customMavenPublishUrl =

mavenArtifactGroup =

enableSpotless = true

enableJUnit = true

deploymentDebug = false
